name: TypeScript Check & Lint
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install tsconfig-paths
        run: npm install --save-dev tsconfig-paths

      - name: TypeScript Check
        run: npx ts-node -r tsconfig-paths/register ./node_modules/typescript/lib/tsc.js --noEmit

      - name: ESLint Check
        run: npx eslint ./src --ext .ts,.tsx
